source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 2.7.1'

gem 'bootsnap', '~> 1.4', require: false
gem 'jbuilder'
gem 'pg'
gem 'puma'
gem 'puma_worker_killer'
gem 'rails', '~> 7.0.2'
gem 'sassc-rails'
gem 'turbolinks', '~> 5'
gem 'uglifier'

gem 'actionpack-action_caching'
gem 'activejob-lockable'
gem 'activejob-perform_later'
gem 'activejob-traffic_control'
gem 'acts_as_commentable_with_threading', github: 'stackshareio/acts_as_commentable_with_threading'
gem 'acts_as_paranoid', github: 'ActsAsParanoid/acts_as_paranoid'
gem 'acts-as-taggable-on'
gem 'acts_as_votable'
gem 'addressable'
gem 'algoliasearch-rails'
gem 'analytics-ruby', require: 'segment'
gem 'angellist_api'
gem 'audited', '~> 5.0'
gem 'awesome_print'
gem 'awesome_print-carrierwave'
gem 'aws-sdk-s3'
gem 'bootstrap-sass' # Bootstrap 3
gem 'buffer', github: 'bufferapp/buffer-ruby'
gem 'carrierwave'
gem 'chronic'
gem 'clearbit', '~> 0.3.3'
gem 'connection_pool'
gem 'customerio'
gem 'devise'
gem 'diffy'
gem 'down'
gem 'dynamic_sitemaps', github: 'lassebunk/dynamic_sitemaps'
gem 'eventbrite', github: 'envoy/eventbrite'
gem 'faraday'
gem 'faraday-http-cache'
gem 'faraday_middleware'
gem 'feedjira'
gem 'fog-aws'
gem 'font-awesome-rails'
gem 'geocoder'
gem 'ginjo-omniauth-slack', require: 'omniauth-slack'
gem 'gitlab'
gem 'google-api-client'
gem 'graphiql-rails'
gem 'graphql', '1.9.3'
gem 'graphql-cache', github: 'stackshareio/graphql-cache', ref: '3c3f378'
gem 'graphql-docs'
gem 'graphql-errors'
gem 'greenhouse_io'
gem 'griddler'
gem 'griddler-sendgrid'
gem 'haml'
gem 'hashie'
gem 'hiredis'
gem 'httparty'
gem 'ipcat'
gem 'jwt'
gem 'kaminari'
gem 'kickbox'
gem 'letter_opener_web'
gem 'listjs-rails'
gem 'lograge'
gem 'mail'
gem 'makara', github: 'stackshareio/makara', ref: 'de7b15e'
gem 'marginalia'
gem 'mechanize'
gem 'metainspector'
gem 'meta-tags'
gem 'mini_magick'
gem 'mini_racer'
gem 'momentjs-rails'
gem 'multi_json'
gem 'newrelic_rpm'
gem 'nokogiri'
gem 'octicons-rails', github: 'stackshareio/octicons-rails'
gem 'octokit'
gem 'omniauth'
gem 'omniauth-azure-oauth2'
gem 'omniauth-bitbucket', github: 'stackshareio/omniauth-bitbucket2', ref: '4aeab99'
gem 'omniauth-github'
gem 'omniauth-gitlab'
gem 'omniauth-google-oauth2'
gem 'omniauth-oauth2-cognito', github: 'arcadia/omniauth-oauth2-cognito'
gem 'omniauth-oktaoauth', github: 'stackshareio/omniauth-oktaoauth', ref: '8ba3d2d'
gem 'omniauth-twitter'
gem 'pghero'
gem 'pg_query'
gem 'popper_js'
gem 'pretender'
gem 'public_suffix'
gem 'pundit'
gem 'rack'
gem 'rack-attack'
gem 'rack-cors', require: 'rack/cors'
gem 'rack-rewrite'
gem 'rack-timeout', require: 'rack/timeout/base'
gem 'rails_admin', github: 'stackshareio/rails_admin'
gem 'ransack', github: 'activerecord-hackery/ransack'
gem 'react_on_rails', '11.3.0' # Unused except in a few old legacy pages
gem 'redcarpet'
gem 'redis', require: ['redis', 'redis/connection/hiredis']
gem 'responders'
gem 'rest-client'
gem 'retryable'
gem 'reverse_markdown'
gem 'roboto'
gem 'ruby-progressbar', require: false
gem 'rubyzip'
gem 'select2-rails'
gem 'sendgrid-ruby', '~> 1.1.6'
gem 'send_with_us'
gem 'sendwithus_ruby_action_mailer'
gem 'sentry-raven'
gem 'sidekiq-cron', github: 'stackshareio/sidekiq-cron', ref: '32eb0a6'
gem 'sidekiq-pro', source: 'https://gems.contribsys.com'
gem 'sidekiq-statistic', github: 'stackshareio/sidekiq-statistic'
gem 'simple_form'
gem 'slack_mrkdwn'
gem 'slack-ruby-client'
gem 'slideshare_api'
gem 'stream-ruby', '~> 3.1.0'
gem 'stringex'
gem 'stripe'
gem 'strong_migrations'
gem 'sweetalert-rails'
gem 'tabler-rubygem'
gem 'tilt'
gem 'twitter'
gem 'uploadcare-rails', github: 'stackshareio/uploadcare-rails'
gem 'url2png'
gem 'wappalyzer', github: 'stackshareio/wappalyzer'
gem 'webpacker'
gem 'yt'

group :development, :test do
  gem 'benchmark-ips'
  gem 'brakeman'
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'factory_bot_rails', '6.1.0', require: false
  gem 'knapsack'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rspec-its'
  gem 'rspec-rails'
  gem 'rspec-retry'
  gem 'rubocop', require: false
  gem 'rubocop-graphql', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'simplecov', require: false
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-commands-rubocop'
  gem 'spring-watcher-listen', github: 'rails/spring-watcher-listen'
end

group :development do
  gem 'active_record_doctor'
  gem 'bullet'
  gem 'listen'
  gem 'table_print'
  gem 'terminal-table'
  gem 'web-console'
end

group :test do
  gem 'database_cleaner'
  gem 'faker'
  gem 'fakeredis', require: 'fakeredis/rspec'
  gem 'fantaskspec'
  gem 'fuubar'
  gem 'launchy'
  gem 'rails-controller-testing'
  gem 'shoulda-matchers'
  gem 'stripe-ruby-mock', '~> 3.0.1', require: 'stripe_mock'
  gem 'webmock'
end
